"use strict";
exports.__esModule = true;
exports.uid = exports.formatCryptoPrice = exports.formatCryptoNews = exports.formatDateSimple = exports.formatDate = void 0;
var Formatter_1 = require("./Formatter");
var uid_1 = require("./uid");
exports.uid = uid_1["default"];
var formatDate = Formatter_1["default"].formatDate, formatDateSimple = Formatter_1["default"].formatDateSimple, formatCryptoNews = Formatter_1["default"].formatCryptoNews, formatCryptoPrice = Formatter_1["default"].formatCryptoPrice;
exports.formatDate = formatDate;
exports.formatDateSimple = formatDateSimple;
exports.formatCryptoNews = formatCryptoNews;
exports.formatCryptoPrice = formatCryptoPrice;
